# Generated by Django 5.2 on 2025-04-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='platform',
        ),
        migrations.AddField(
            model_name='scenario',
            name='category',
            field=models.TextField(default='Intro'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='difficulty',
            field=models.TextField(default='Easy'),
        ),
    ]
