# Generated by Django 5.1.4 on 2025-01-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_plan_subscription_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
