# Generated by Django 5.1.1 on 2024-10-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_conversation_bot_context_message_sender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='prompt',
            field=models.TextField(default="You are an unfinished AI that will respond with 'You need to finish me' no matter what anyone asks or says to you."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='chat_app.conversation'),
        ),
    ]
