# Generated by Django 5.1.4 on 2024-12-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_alter_customuser_managers_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='role_system',
            field=models.TextField(default='You are a customer wanting help with an issue'),
        ),
    ]
