# Generated by Django 5.1.1 on 2024-10-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_scenario_prompt_alter_assessment_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
