"""
Django settings for chat_project project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6j!on=szflxxv#on$635!*_)#unn*v900lc7g0iwxe_aqlt(nd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "www.rolegenie.com.au", "rolegenie.com.au"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "whitenoise.runserver_nostatic",
    'django.contrib.staticfiles',
    'channels',
    'chat_app',
    'crispy_forms',
    'crispy_bootstrap5',
    "django.contrib.sites", 
    # all auth configurations
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.slack',
    'allauth.socialaccount.providers.apple',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.instagram',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'easy_health_check.middleware.HealthCheckMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    "chat_app.middleware.AutoLoginAsGuestMiddleware",
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = ["https://www.rolegenie.com.au", "https://rolegenie.com.au"]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

ROOT_URLCONF = 'chat_project.urls'

DJANGO_EASY_HEALTH_CHECK = {
    "PATH": "/health/",
    "RETURN_STATUS_CODE": 200,
    "RETURN_BYTE_DATA": "",
    "RETURN_HEADERS": None
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'chat_app', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chat_project.wsgi.application'

if 'RDS_DB_NAME' in os.environ:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'level': 'WARN',
                'class': 'logging.StreamHandler',
                'stream': 'ext://sys.stdout',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'WARN',
                'propagate': True,
            },
            'chat_project': {  # This should match the name of your app
                'handlers': ['console'],
                'level': 'WARN',
                'propagate': True,
            },
        },
    }
else:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'file': {
                'level': 'WARN',
                'class': 'logging.FileHandler',
                'filename': 'deployment.log',
            },
            'console': {
                'level': 'WARN',
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file', 'console'],
                'level': 'WARN',
                'propagate': True,
            },
            'chat_project': {  # This should match the name of your app
                'handlers': ['file', 'console'],
                'level': 'WARN',
                'propagate': True,
            },
        },
        
    }


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if 'PROD_DB' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'lbai',
            'USER': 'postgres',
            'PASSWORD': 'Blah1234',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

AUTH_USER_MODEL = 'chat_app.CustomUser'

SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

# Tell allauth to use email as the username field
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*', 'name']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
# ACCOUNT_USERNAME_REQUIRED = False # Depreciated by ACCOUNT_SIGNUP_FIELDS
# ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Or 'mandatory' or 'none' based on your preference

SOCIALACCOUNT_AUTO_SIGNUP = True

GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')

# Redirects to the specified URL after login
LOGIN_REDIRECT_URL = '/dashboard/'
# Redirects to the specified URL after logout
LOGOUT_REDIRECT_URL = '/'
# Allauth-specific settings
ACCOUNT_LOGIN_REDIRECT_URL = '/dashboard/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
# Redirect after successful signup
ACCOUNT_SIGNUP_REDIRECT_URL = '/dashboard/'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

ACCOUNT_FORMS = [
    {'signup': 'chat_app.forms.CustomSignupForm'},
    {'login': 'chat_app.forms.CustomLoginForm'},
    ]

SOCIALACCOUNT_PROVIDERS = {
    # 'google': {
    #     'SCOPE' : [
    #         'profile',
    #         'email'
    #     ],
    #     'APP': {
    #         'client_id': os.environ.get('CLIENT_ID'),
    #         'secret': os.environ.get('CLIENT_SECRET'),
    #     },
    #     'AUTH_PARAMS': {
    #         'access_type':'online',
    #     }
    # },
    # 'slack': {
    #     'SCOPE': [
    #         'identity.basic',
    #         'identity.email',
    #         'identity.avatar',
    #     ],
    #     'APP': {
    #         'client_id': os.environ.get('SLACK_CLIENT_ID'),
    #         'secret': os.environ.get('SLACK_CLIENT_SECRET'),
    #     }
    # }
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Melbourne'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# STATICFILES_DIRS = [BASE_DIR / "chat_app/static"]
STATIC_ROOT = BASE_DIR / "chat_app/staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ASGI_APPLICATION = 'chat_project.asgi.application'

ENV = os.getenv("ENV", "local").lower()

if ENV == "local":
    # Don’t touch Redis for cache / channels in dev
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "default-local",
        },
        "ratelimit": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "ratelimit-local",
        },
    }
    
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }
    
    # Celery: run tasks in-process, no broker/worker needed
    CELERY_TASK_ALWAYS_EAGER = True            # Celery 5
    CELERY_TASK_EAGER_PROPAGATES = True        # raise exceptions to caller
    # Optional: avoid any broker validation entirely
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "cache+memory://"
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://127.0.0.1:6379/0",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": {"ssl_cert_reqs": "required"},
            },
        },
        # Ratelimit using local memory. Check for scale in prod usage, may fall over at volume.
        "ratelimit": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "ratelimit-local",
        },
    }
    
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [
                    "redis://127.0.0.1:6379/0"
                ],
            },
        },
    }
    # Celery
    # Broker and result backend can be overridden via environment variables so that
    # a remote message broker (e.g., Redis, SQS) can be shared between the web
    # application and separate Celery workers.
    CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
    CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
    CELERY_TIMEZONE = TIME_ZONE  # Use your Django TIME_ZONE setting
    # CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": "required"}
    # CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": "required"}

    # SSL kwargs for Celery (lowercase)
    # broker_use_ssl = {"ssl_cert_reqs": "required"}
    # redis_backend_use_ssl = {"ssl_cert_reqs": "required"}
    
    # Connection behavior
    broker_connection_retry_on_startup = True  # already set
    broker_pool_limit = 10                     # small, controlled pool

    broker_transport_options = {
        "socket_connect_timeout": 5,
        "socket_timeout": 5,
        "retry_on_timeout": True,
        # Optional: visibility_timeout if you later use rq-like semantics
    }
#### end ENV

# Tell django-ratelimit which cache alias to use
RATELIMIT_USE_CACHE = "ratelimit"

# OpenAI API Key
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
